# 远程主题配置
remote_theme: "pages-themes/leap-day@2.0"

# 网站基本信息

- title: operation
  url: introduction.html

- title: Configuration
  url: configuration.html

- title: Deployment
  url: deployment.html
  
  <h2>{{ site.data.samplelist.docs_list_title }}</h2>
<ul>
   {% for item in site.data.samplelist.docs %}
      <li><a href="{{ item.url }}">{{ item.title }}</a></li>
   {% endfor %}
</ul>
